#if defined (			__ERROR_CODES__				)
/*---------------------------------------------------------------------------*/
	ERR_NONE, ERR_INVALID, ERR_nullPTR, ERR_INITFAIL, 
	ERR_NOTIMPLEM, ERR_FAIL, ERR_BUSY,

	ERR_SEGFAULT, ERR_ABORT,

	DATAERR_MEMALLOC, DATAERR_SIZETOOLARGE, 	
	DATAERR_OUTOFRANGE,DATAERR_LIMIT, 		
	DATAERR_EMPTY, DATAERR_DSN,		

	MEMERR_OVERFLOW, MEMERR_INITFAIL, MEMERR_LEAK, MEMERR_INVALIDSIZE,	

	STRINGERR_REGEX, STRINGERR_FORMAT, STRINGERR_ENCODING, STRINGERR_OUTOFRANGE,
#else




#endif




