
// This file was automatically generated to support up to 150 arguments using _Generic.

#include <stddef.h> // For size_t

/**
 * __ARGS_calc_size(A): Calculates the size of the argument A.
 * Special case: Treats string literals (char*) as sizeof(char*) instead of sizeof("literal"),
 * which is useful if you intend to copy the pointer, not the entire literal content.
 */
#define __ARGS_calc_size(A) _Generic((A), const char*: sizeof(const char*), char*: sizeof(char*), default: sizeof(typeof(A)))

// The core recursive step: Calculate size of A and call the next helper.
#define __ARGS_calc_size_and_next(A, next_num, ...) (__ARGS_calc_size(A) + __ARGS_sizeof_sum_helper_##next_num(__VA_ARGS__))

#define __ARGS_sizeof_sum_helper_1(A) __ARGS_calc_size(A)
// Recursive Helper Definitions:
#define __ARGS_sizeof_sum_helper_2(A, ...) __ARGS_calc_size_and_next(A, 1, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_3(A, ...) __ARGS_calc_size_and_next(A, 2, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_4(A, ...) __ARGS_calc_size_and_next(A, 3, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_5(A, ...) __ARGS_calc_size_and_next(A, 4, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_6(A, ...) __ARGS_calc_size_and_next(A, 5, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_7(A, ...) __ARGS_calc_size_and_next(A, 6, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_8(A, ...) __ARGS_calc_size_and_next(A, 7, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_9(A, ...) __ARGS_calc_size_and_next(A, 8, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_10(A, ...) __ARGS_calc_size_and_next(A, 9, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_11(A, ...) __ARGS_calc_size_and_next(A, 10, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_12(A, ...) __ARGS_calc_size_and_next(A, 11, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_13(A, ...) __ARGS_calc_size_and_next(A, 12, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_14(A, ...) __ARGS_calc_size_and_next(A, 13, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_15(A, ...) __ARGS_calc_size_and_next(A, 14, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_16(A, ...) __ARGS_calc_size_and_next(A, 15, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_17(A, ...) __ARGS_calc_size_and_next(A, 16, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_18(A, ...) __ARGS_calc_size_and_next(A, 17, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_19(A, ...) __ARGS_calc_size_and_next(A, 18, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_20(A, ...) __ARGS_calc_size_and_next(A, 19, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_21(A, ...) __ARGS_calc_size_and_next(A, 20, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_22(A, ...) __ARGS_calc_size_and_next(A, 21, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_23(A, ...) __ARGS_calc_size_and_next(A, 22, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_24(A, ...) __ARGS_calc_size_and_next(A, 23, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_25(A, ...) __ARGS_calc_size_and_next(A, 24, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_26(A, ...) __ARGS_calc_size_and_next(A, 25, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_27(A, ...) __ARGS_calc_size_and_next(A, 26, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_28(A, ...) __ARGS_calc_size_and_next(A, 27, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_29(A, ...) __ARGS_calc_size_and_next(A, 28, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_30(A, ...) __ARGS_calc_size_and_next(A, 29, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_31(A, ...) __ARGS_calc_size_and_next(A, 30, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_32(A, ...) __ARGS_calc_size_and_next(A, 31, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_33(A, ...) __ARGS_calc_size_and_next(A, 32, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_34(A, ...) __ARGS_calc_size_and_next(A, 33, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_35(A, ...) __ARGS_calc_size_and_next(A, 34, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_36(A, ...) __ARGS_calc_size_and_next(A, 35, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_37(A, ...) __ARGS_calc_size_and_next(A, 36, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_38(A, ...) __ARGS_calc_size_and_next(A, 37, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_39(A, ...) __ARGS_calc_size_and_next(A, 38, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_40(A, ...) __ARGS_calc_size_and_next(A, 39, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_41(A, ...) __ARGS_calc_size_and_next(A, 40, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_42(A, ...) __ARGS_calc_size_and_next(A, 41, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_43(A, ...) __ARGS_calc_size_and_next(A, 42, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_44(A, ...) __ARGS_calc_size_and_next(A, 43, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_45(A, ...) __ARGS_calc_size_and_next(A, 44, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_46(A, ...) __ARGS_calc_size_and_next(A, 45, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_47(A, ...) __ARGS_calc_size_and_next(A, 46, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_48(A, ...) __ARGS_calc_size_and_next(A, 47, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_49(A, ...) __ARGS_calc_size_and_next(A, 48, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_50(A, ...) __ARGS_calc_size_and_next(A, 49, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_51(A, ...) __ARGS_calc_size_and_next(A, 50, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_52(A, ...) __ARGS_calc_size_and_next(A, 51, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_53(A, ...) __ARGS_calc_size_and_next(A, 52, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_54(A, ...) __ARGS_calc_size_and_next(A, 53, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_55(A, ...) __ARGS_calc_size_and_next(A, 54, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_56(A, ...) __ARGS_calc_size_and_next(A, 55, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_57(A, ...) __ARGS_calc_size_and_next(A, 56, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_58(A, ...) __ARGS_calc_size_and_next(A, 57, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_59(A, ...) __ARGS_calc_size_and_next(A, 58, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_60(A, ...) __ARGS_calc_size_and_next(A, 59, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_61(A, ...) __ARGS_calc_size_and_next(A, 60, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_62(A, ...) __ARGS_calc_size_and_next(A, 61, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_63(A, ...) __ARGS_calc_size_and_next(A, 62, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_64(A, ...) __ARGS_calc_size_and_next(A, 63, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_65(A, ...) __ARGS_calc_size_and_next(A, 64, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_66(A, ...) __ARGS_calc_size_and_next(A, 65, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_67(A, ...) __ARGS_calc_size_and_next(A, 66, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_68(A, ...) __ARGS_calc_size_and_next(A, 67, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_69(A, ...) __ARGS_calc_size_and_next(A, 68, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_70(A, ...) __ARGS_calc_size_and_next(A, 69, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_71(A, ...) __ARGS_calc_size_and_next(A, 70, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_72(A, ...) __ARGS_calc_size_and_next(A, 71, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_73(A, ...) __ARGS_calc_size_and_next(A, 72, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_74(A, ...) __ARGS_calc_size_and_next(A, 73, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_75(A, ...) __ARGS_calc_size_and_next(A, 74, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_76(A, ...) __ARGS_calc_size_and_next(A, 75, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_77(A, ...) __ARGS_calc_size_and_next(A, 76, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_78(A, ...) __ARGS_calc_size_and_next(A, 77, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_79(A, ...) __ARGS_calc_size_and_next(A, 78, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_80(A, ...) __ARGS_calc_size_and_next(A, 79, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_81(A, ...) __ARGS_calc_size_and_next(A, 80, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_82(A, ...) __ARGS_calc_size_and_next(A, 81, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_83(A, ...) __ARGS_calc_size_and_next(A, 82, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_84(A, ...) __ARGS_calc_size_and_next(A, 83, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_85(A, ...) __ARGS_calc_size_and_next(A, 84, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_86(A, ...) __ARGS_calc_size_and_next(A, 85, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_87(A, ...) __ARGS_calc_size_and_next(A, 86, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_88(A, ...) __ARGS_calc_size_and_next(A, 87, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_89(A, ...) __ARGS_calc_size_and_next(A, 88, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_90(A, ...) __ARGS_calc_size_and_next(A, 89, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_91(A, ...) __ARGS_calc_size_and_next(A, 90, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_92(A, ...) __ARGS_calc_size_and_next(A, 91, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_93(A, ...) __ARGS_calc_size_and_next(A, 92, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_94(A, ...) __ARGS_calc_size_and_next(A, 93, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_95(A, ...) __ARGS_calc_size_and_next(A, 94, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_96(A, ...) __ARGS_calc_size_and_next(A, 95, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_97(A, ...) __ARGS_calc_size_and_next(A, 96, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_98(A, ...) __ARGS_calc_size_and_next(A, 97, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_99(A, ...) __ARGS_calc_size_and_next(A, 98, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_100(A, ...) __ARGS_calc_size_and_next(A, 99, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_101(A, ...) __ARGS_calc_size_and_next(A, 100, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_102(A, ...) __ARGS_calc_size_and_next(A, 101, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_103(A, ...) __ARGS_calc_size_and_next(A, 102, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_104(A, ...) __ARGS_calc_size_and_next(A, 103, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_105(A, ...) __ARGS_calc_size_and_next(A, 104, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_106(A, ...) __ARGS_calc_size_and_next(A, 105, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_107(A, ...) __ARGS_calc_size_and_next(A, 106, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_108(A, ...) __ARGS_calc_size_and_next(A, 107, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_109(A, ...) __ARGS_calc_size_and_next(A, 108, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_110(A, ...) __ARGS_calc_size_and_next(A, 109, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_111(A, ...) __ARGS_calc_size_and_next(A, 110, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_112(A, ...) __ARGS_calc_size_and_next(A, 111, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_113(A, ...) __ARGS_calc_size_and_next(A, 112, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_114(A, ...) __ARGS_calc_size_and_next(A, 113, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_115(A, ...) __ARGS_calc_size_and_next(A, 114, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_116(A, ...) __ARGS_calc_size_and_next(A, 115, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_117(A, ...) __ARGS_calc_size_and_next(A, 116, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_118(A, ...) __ARGS_calc_size_and_next(A, 117, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_119(A, ...) __ARGS_calc_size_and_next(A, 118, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_120(A, ...) __ARGS_calc_size_and_next(A, 119, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_121(A, ...) __ARGS_calc_size_and_next(A, 120, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_122(A, ...) __ARGS_calc_size_and_next(A, 121, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_123(A, ...) __ARGS_calc_size_and_next(A, 122, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_124(A, ...) __ARGS_calc_size_and_next(A, 123, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_125(A, ...) __ARGS_calc_size_and_next(A, 124, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_126(A, ...) __ARGS_calc_size_and_next(A, 125, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_127(A, ...) __ARGS_calc_size_and_next(A, 126, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_128(A, ...) __ARGS_calc_size_and_next(A, 127, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_129(A, ...) __ARGS_calc_size_and_next(A, 128, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_130(A, ...) __ARGS_calc_size_and_next(A, 129, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_131(A, ...) __ARGS_calc_size_and_next(A, 130, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_132(A, ...) __ARGS_calc_size_and_next(A, 131, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_133(A, ...) __ARGS_calc_size_and_next(A, 132, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_134(A, ...) __ARGS_calc_size_and_next(A, 133, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_135(A, ...) __ARGS_calc_size_and_next(A, 134, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_136(A, ...) __ARGS_calc_size_and_next(A, 135, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_137(A, ...) __ARGS_calc_size_and_next(A, 136, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_138(A, ...) __ARGS_calc_size_and_next(A, 137, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_139(A, ...) __ARGS_calc_size_and_next(A, 138, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_140(A, ...) __ARGS_calc_size_and_next(A, 139, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_141(A, ...) __ARGS_calc_size_and_next(A, 140, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_142(A, ...) __ARGS_calc_size_and_next(A, 141, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_143(A, ...) __ARGS_calc_size_and_next(A, 142, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_144(A, ...) __ARGS_calc_size_and_next(A, 143, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_145(A, ...) __ARGS_calc_size_and_next(A, 144, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_146(A, ...) __ARGS_calc_size_and_next(A, 145, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_147(A, ...) __ARGS_calc_size_and_next(A, 146, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_148(A, ...) __ARGS_calc_size_and_next(A, 147, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_149(A, ...) __ARGS_calc_size_and_next(A, 148, __VA_ARGS__)
#define __ARGS_sizeof_sum_helper_150(A, ...) __ARGS_calc_size_and_next(A, 149, __VA_ARGS__)

// --- PART 3: Argument Counting and Dispatch --- 
#define __ARGS_SELECT_MACRO(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124, _125, _126, _127, _128, _129, _130, _131, _132, _133, _134, _135, _136, _137, _138, _139, _140, _141, _142, _143, _144, _145, _146, _147, _148, _149, _150, NAME, ...) NAME
#define __ARGS_GET_MACRO(...) __ARGS_SELECT_MACRO(__VA_ARGS__, __ARGS_sizeof_sum_helper_150, __ARGS_sizeof_sum_helper_149, __ARGS_sizeof_sum_helper_148, __ARGS_sizeof_sum_helper_147, __ARGS_sizeof_sum_helper_146, __ARGS_sizeof_sum_helper_145, __ARGS_sizeof_sum_helper_144, __ARGS_sizeof_sum_helper_143, __ARGS_sizeof_sum_helper_142, __ARGS_sizeof_sum_helper_141, __ARGS_sizeof_sum_helper_140, __ARGS_sizeof_sum_helper_139, __ARGS_sizeof_sum_helper_138, __ARGS_sizeof_sum_helper_137, __ARGS_sizeof_sum_helper_136, __ARGS_sizeof_sum_helper_135, __ARGS_sizeof_sum_helper_134, __ARGS_sizeof_sum_helper_133, __ARGS_sizeof_sum_helper_132, __ARGS_sizeof_sum_helper_131, __ARGS_sizeof_sum_helper_130, __ARGS_sizeof_sum_helper_129, __ARGS_sizeof_sum_helper_128, __ARGS_sizeof_sum_helper_127, __ARGS_sizeof_sum_helper_126, __ARGS_sizeof_sum_helper_125, __ARGS_sizeof_sum_helper_124, __ARGS_sizeof_sum_helper_123, __ARGS_sizeof_sum_helper_122, __ARGS_sizeof_sum_helper_121, __ARGS_sizeof_sum_helper_120, __ARGS_sizeof_sum_helper_119, __ARGS_sizeof_sum_helper_118, __ARGS_sizeof_sum_helper_117, __ARGS_sizeof_sum_helper_116, __ARGS_sizeof_sum_helper_115, __ARGS_sizeof_sum_helper_114, __ARGS_sizeof_sum_helper_113, __ARGS_sizeof_sum_helper_112, __ARGS_sizeof_sum_helper_111, __ARGS_sizeof_sum_helper_110, __ARGS_sizeof_sum_helper_109, __ARGS_sizeof_sum_helper_108, __ARGS_sizeof_sum_helper_107, __ARGS_sizeof_sum_helper_106, __ARGS_sizeof_sum_helper_105, __ARGS_sizeof_sum_helper_104, __ARGS_sizeof_sum_helper_103, __ARGS_sizeof_sum_helper_102, __ARGS_sizeof_sum_helper_101, __ARGS_sizeof_sum_helper_100, __ARGS_sizeof_sum_helper_99, __ARGS_sizeof_sum_helper_98, __ARGS_sizeof_sum_helper_97, __ARGS_sizeof_sum_helper_96, __ARGS_sizeof_sum_helper_95, __ARGS_sizeof_sum_helper_94, __ARGS_sizeof_sum_helper_93, __ARGS_sizeof_sum_helper_92, __ARGS_sizeof_sum_helper_91, __ARGS_sizeof_sum_helper_90, __ARGS_sizeof_sum_helper_89, __ARGS_sizeof_sum_helper_88, __ARGS_sizeof_sum_helper_87, __ARGS_sizeof_sum_helper_86, __ARGS_sizeof_sum_helper_85, __ARGS_sizeof_sum_helper_84, __ARGS_sizeof_sum_helper_83, __ARGS_sizeof_sum_helper_82, __ARGS_sizeof_sum_helper_81, __ARGS_sizeof_sum_helper_80, __ARGS_sizeof_sum_helper_79, __ARGS_sizeof_sum_helper_78, __ARGS_sizeof_sum_helper_77, __ARGS_sizeof_sum_helper_76, __ARGS_sizeof_sum_helper_75, __ARGS_sizeof_sum_helper_74, __ARGS_sizeof_sum_helper_73, __ARGS_sizeof_sum_helper_72, __ARGS_sizeof_sum_helper_71, __ARGS_sizeof_sum_helper_70, __ARGS_sizeof_sum_helper_69, __ARGS_sizeof_sum_helper_68, __ARGS_sizeof_sum_helper_67, __ARGS_sizeof_sum_helper_66, __ARGS_sizeof_sum_helper_65, __ARGS_sizeof_sum_helper_64, __ARGS_sizeof_sum_helper_63, __ARGS_sizeof_sum_helper_62, __ARGS_sizeof_sum_helper_61, __ARGS_sizeof_sum_helper_60, __ARGS_sizeof_sum_helper_59, __ARGS_sizeof_sum_helper_58, __ARGS_sizeof_sum_helper_57, __ARGS_sizeof_sum_helper_56, __ARGS_sizeof_sum_helper_55, __ARGS_sizeof_sum_helper_54, __ARGS_sizeof_sum_helper_53, __ARGS_sizeof_sum_helper_52, __ARGS_sizeof_sum_helper_51, __ARGS_sizeof_sum_helper_50, __ARGS_sizeof_sum_helper_49, __ARGS_sizeof_sum_helper_48, __ARGS_sizeof_sum_helper_47, __ARGS_sizeof_sum_helper_46, __ARGS_sizeof_sum_helper_45, __ARGS_sizeof_sum_helper_44, __ARGS_sizeof_sum_helper_43, __ARGS_sizeof_sum_helper_42, __ARGS_sizeof_sum_helper_41, __ARGS_sizeof_sum_helper_40, __ARGS_sizeof_sum_helper_39, __ARGS_sizeof_sum_helper_38, __ARGS_sizeof_sum_helper_37, __ARGS_sizeof_sum_helper_36, __ARGS_sizeof_sum_helper_35, __ARGS_sizeof_sum_helper_34, __ARGS_sizeof_sum_helper_33, __ARGS_sizeof_sum_helper_32, __ARGS_sizeof_sum_helper_31, __ARGS_sizeof_sum_helper_30, __ARGS_sizeof_sum_helper_29, __ARGS_sizeof_sum_helper_28, __ARGS_sizeof_sum_helper_27, __ARGS_sizeof_sum_helper_26, __ARGS_sizeof_sum_helper_25, __ARGS_sizeof_sum_helper_24, __ARGS_sizeof_sum_helper_23, __ARGS_sizeof_sum_helper_22, __ARGS_sizeof_sum_helper_21, __ARGS_sizeof_sum_helper_20, __ARGS_sizeof_sum_helper_19, __ARGS_sizeof_sum_helper_18, __ARGS_sizeof_sum_helper_17, __ARGS_sizeof_sum_helper_16, __ARGS_sizeof_sum_helper_15, __ARGS_sizeof_sum_helper_14, __ARGS_sizeof_sum_helper_13, __ARGS_sizeof_sum_helper_12, __ARGS_sizeof_sum_helper_11, __ARGS_sizeof_sum_helper_10, __ARGS_sizeof_sum_helper_9, __ARGS_sizeof_sum_helper_8, __ARGS_sizeof_sum_helper_7, __ARGS_sizeof_sum_helper_6, __ARGS_sizeof_sum_helper_5, __ARGS_sizeof_sum_helper_4, __ARGS_sizeof_sum_helper_3, __ARGS_sizeof_sum_helper_2, __ARGS_sizeof_sum_helper_1)

// --- PART 4: The Final Combined Macro --- 
#define __ARGS_sizeof_sum_helper(...) __ARGS_GET_MACRO(__VA_ARGS__)(__VA_ARGS__)
